name: covid19_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^5.7.2
  mbi: ^0.0.9
  google_fonts: ^1.1.0
  fl_chart: ^0.11.1
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  pull_to_refresh: ^1.6.2
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Corona
      fonts:
        - asset: assets/fonts/Corona.ttf
  assets:
    - assets/Corona.png

